### ISSUE TITLE
Install script fails with PermissionError: [Errno 13] Permission denied: './.env'

### ISSUE THREAD

**Issue by ratio91** [getumbrel/umbrel#1137]
I am trying to install umbrel 0.4.9 on an Ubuntu server 20 machine. When I run the install script (` sudo ./scripts/start`) it fails with the following error: 

```
Traceback (most recent call last):
  File "/snap/docker/1125/bin/docker-compose", line 33, in <module>
    sys.exit(load_entry_point('docker-compose==1.25.5', 'console_scripts', 'docker-compose')())
  File "/snap/docker/1125/lib/python3.6/site-packages/compose/cli/main.py", line 72, in main
    command()
  File "/snap/docker/1125/lib/python3.6/site-packages/compose/cli/main.py", line 125, in perform_command
    project = project_from_options('.', options)
  File "/snap/docker/1125/lib/python3.6/site-packages/compose/cli/command.py", line 47, in project_from_options
    environment = Environment.from_env_file(override_dir or project_dir, environment_file)
  File "/snap/docker/1125/lib/python3.6/site-packages/compose/config/environment.py", line 77, in from_env_file
    instance = _initialize()
  File "/snap/docker/1125/lib/python3.6/site-packages/compose/config/environment.py", line 72, in _initialize
    return cls(env_vars_from_file(env_file_path))
  File "/snap/docker/1125/lib/python3.6/site-packages/compose/config/environment.py", line 43, in env_vars_from_file
    with contextlib.closing(codecs.open(filename, 'r', 'utf-8-sig')) as fileobj:
  File "/snap/docker/1125/usr/lib/python3.6/codecs.py", line 897, in open
    file = builtins.open(filename, mode, buffering)
PermissionError: [Errno 13] Permission denied: './.env'

```

Any idea what I'm missing here?
Thank you!

**Comment by louneskmt** [comment]
Looks like a permission issue. Can you try to chmod 777 the file `.env`?

**Comment by bfg86** [comment]
I had the same issue. Worked around it by uninstalling the snap version of docker, and installing docker.io and docker-compose via apt. StackOverflow: https://stackoverflow.com/questions/53344380/errno-13-while-running-docker-compose-up

**Comment by TomKalina** [comment]
> I had the same issue. Worked around it by uninstalling the snap version of docker, and installing docker.io and docker-compose via apt. StackOverflow: https://stackoverflow.com/questions/53344380/errno-13-while-running-docker-compose-up

Same problem, same solution :)
