### ISSUE TITLE
[Docker] Unable to upgrade to 0.4.11 from 0.4.9

### ISSUE THREAD

**Issue by Hukuma1** [getumbrel/umbrel#1196]
On a working `0.4.9` docker install. I just extracted the files from `0.4.11` to my folder and run the start script.

```
root@umbrel:/umbrel# ./scripts/start
Skipping status update when not on Umbrel OS

======================================
============= STARTING ===============
============== UMBREL ================
======================================

Setting environment variables...

Starting karen...

Starting status monitors...
Starting memory monitor...

Starting backup monitor...

Starting decoy backup trigger...


Starting Docker services...

WARNING: The TOR_SERVER_IP variable is not set. Defaulting to a blank string.
Creating network "umbrel_main_network" with the default driver
Creating tor                 ... done
Creating dashboard           ... done
Creating electrs             ... done
Creating umbrel_tor_server_1 ... done
Creating manager             ... done
Creating nginx               ... done
Creating lnd                 ... done
Creating bitcoin             ... done
Creating middleware          ... done
Creating neutrino-switcher   ... done

Removing status server iptables entry...
Exiting iptables setup when not on Umbrel OS

Starting installed apps...


Umbrel is now accessible at
  http://umbrel.local
  http://172.17.0.4
  http://superlongblahblahaddress.onion
Skipping status update when not on Umbrel OS
```

As with previous versions, I had to edit the start script to allow my actual IP:PORT to access the WebUI. (Otherwise CORS error) So even though I can login, there are probably other places I have to add in my new IP:PORT? I see a new warning above regarding `TOR_SERVER_IP`, do I set that to my actual IP somewhere?

```
:1 [DOM] Input elements should have autocomplete attributes (suggested: "new-password"): (More info: https://goo.gl/9p2vKq) <input data-v-1bdac0da placeholder=​"Password" type=​"password" class=​"card-input w-100" data-com.bitwarden.browser.user-edited=​"yes" disabled=​"disabled">​
api/v1/bitcoind/info/sync:1 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
api.js:100 Error: Request failed with status code 500
    at t.exports (createError.js:16:15)
    at t.exports (settle.js:17:12)
    at XMLHttpRequest.f.onreadystatechange (xhr.js:61:7)
(anonymous) @ api.js:100
manager-api/v1/external/price:1 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
api.js:100 Error: Request failed with status code 500
    at t.exports (createError.js:16:15)
    at t.exports (settle.js:17:12)
    at XMLHttpRequest.f.onreadystatechange (xhr.js:61:7)
(anonymous) @ api.js:100
api/v1/bitcoind/info/sync:1 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
api.js:100 Error: Request failed with status code 500
    at t.exports (createError.js:16:15)
    at t.exports (settle.js:17:12)
    at XMLHttpRequest.f.onreadystatechange (xhr.js:61:7)
(anonymous) @ api.js:100
api/v1/lnd/channel:1 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
api.js:100 Error: Request failed with status code 500
    at t.exports (createError.js:16:15)
    at t.exports (settle.js:17:12)
    at XMLHttpRequest.f.onreadystatechange (xhr.js:61:7)
(anonymous) @ api.js:100
api/v1/lnd/info/sync:1 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
api.js:100 Error: Request failed with status code 500
    at t.exports (createError.js:16:15)
    at t.exports (settle.js:17:12)
    at XMLHttpRequest.f.onreadystatechange (xhr.js:61:7)
(anonymous) @ api.js:100
api/v1/lnd/lightning/invoices:1 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
api.js:100 Error: Request failed with status code 500
    at t.exports (createError.js:16:15)
    at t.exports (settle.js:17:12)
    at XMLHttpRequest.f.onreadystatechange (xhr.js:61:7)
(anonymous) @ api.js:100
api/v1/lnd/transaction:1 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
api.js:100 Error: Request failed with status code 500
    at t.exports (createError.js:16:15)
    at t.exports (settle.js:17:12)
    at XMLHttpRequest.f.onreadystatechange (xhr.js:61:7)
(anonymous) @ api.js:100
api/v1/lnd/wallet/btc:1 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
api.js:100 Error: Request failed with status code 500
    at t.exports (createError.js:16:15)
    at t.exports (settle.js:17:12)
    at XMLHttpRequest.f.onreadystatechange (xhr.js:61:7)
(anonymous) @ api.js:100
api/v1/lnd/lightning/payments:1 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
api.js:100 Error: Request failed with status code 500
    at t.exports (createError.js:16:15)
    at t.exports (settle.js:17:12)
    at XMLHttpRequest.f.onreadystatechange (xhr.js:61:7)
(anonymous) @ api.js:100
api/v1/lnd/wallet/btc:1 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
api.js:100 Error: Request failed with status code 500
    at t.exports (createError.js:16:15)
    at t.exports (settle.js:17:12)
    at XMLHttpRequest.f.onreadystatechange (xhr.js:61:7)
(anonymous) @ api.js:100
api/v1/lnd/lightning/invoices:1 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
api.js:100 Error: Request failed with status code 500
    at t.exports (createError.js:16:15)
    at t.exports (settle.js:17:12)
    at XMLHttpRequest.f.onreadystatechange (xhr.js:61:7)
(anonymous) @ api.js:100
api/v1/lnd/transaction:1 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
api.js:100 Error: Request failed with status code 500
    at t.exports (createError.js:16:15)
    at t.exports (settle.js:17:12)
    at XMLHttpRequest.f.onreadystatechange (xhr.js:61:7)
(anonymous) @ api.js:100
manager-api/v1/external/price:1 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
api.js:100 Error: Request failed with status code 500
    at t.exports (createError.js:16:15)
    at t.exports (settle.js:17:12)
    at XMLHttpRequest.f.onreadystatechange (xhr.js:61:7)
(anonymous) @ api.js:100
api/v1/lnd/info/sync:1 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
api.js:100 Error: Request failed with status code 500
    at t.exports (createError.js:16:15)
    at t.exports (settle.js:17:12)
    at XMLHttpRequest.f.onreadystatechange (xhr.js:61:7)
(anonymous) @ api.js:100
api/v1/lnd/channel:1 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
api.js:100 Error: Request failed with status code 500
    at t.exports (createError.js:16:15)
    at t.exports (settle.js:17:12)
    at XMLHttpRequest.f.onreadystatechange (xhr.js:61:7)
(anonymous) @ api.js:100
api/v1/bitcoind/info/sync:1 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
api.js:100 Error: Request failed with status code 500
    at t.exports (createError.js:16:15)
    at t.exports (settle.js:17:12)
    at XMLHttpRequest.f.onreadystatechange (xhr.js:61:7)
(anonymous) @ api.js:100
api/v1/lnd/lightning/payments:1 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
api.js:100 Error: Request failed with status code 500
    at t.exports (createError.js:16:15)
    at t.exports (settle.js:17:12)
    at XMLHttpRequest.f.onreadystatechange (xhr.js:61:7)
(anonymous) @ api.js:100
api/v1/bitcoind/info/sync:1 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
api.js:100 Error: Request failed with status code 500
    at t.exports (createError.js:16:15)
    at t.exports (settle.js:17:12)
    at XMLHttpRequest.f.onreadystatechange (xhr.js:61:7)
(anonymous) @ api.js:100
api/v1/bitcoind/info/sync:1 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
api.js:100 Error: Request failed with status code 500
    at t.exports (createError.js:16:15)
    at t.exports (settle.js:17:12)
    at XMLHttpRequest.f.onreadystatechange (xhr.js:61:7)
```

```
Umbrel logs
=====================
= Umbrel debug info =
=====================

Umbrel version
--------------
0.4.11

Memory usage
------------
              total        used        free      shared  buff/cache   available
Mem:            15G        4.6G        239M         77M         10G         10G
Swap:           16G        1.4G         14G

total: 29.7%
system: 29.7%
tor: 0%
lnd: 0%
electrs: 0%
bitcoin: 0%

Memory monitor logs
-------------------
   2600 pts/4    S      0:00 bash ./scripts/memory-monitor
Memory monitor is already running
   2600 pts/4    S      0:00 bash ./scripts/memory-monitor
Memory monitor is already running
   2600 pts/4    S      0:00 bash ./scripts/memory-monitor
  28343 pts/6    R+     0:00 bash ./scripts/memory-monitor
Memory monitor is already running
    215 pts/2    R+     0:00 bash ./scripts/memory-monitor
Memory monitor is already running
2022-01-17 18:33:09 Memory monitor running!

Filesystem information
----------------------
Filesystem      Size  Used Avail Use% Mounted on
overlay          31G   29G  1.1G  97% /
/dev/sda1        13T  1.3T   12T  10% /umbrel

Karen logs
----------

./karen: line 68: /umbrel/events/triggers/: Is a directory
Got signal: 
karen is getting triggered!
./karen: line 68: /umbrel/events/triggers/: Is a directory
Got signal: change-password
karen is getting triggered!
This script must only be run on Umbrel OS
Got signal: debug
karen is getting triggered!
No such service: tor
Debug result file generated
Got signal: debug
karen is getting triggered!
No such service: tor
Debug result file generated
   6099 pts/6    S      0:00 bash ./karen
   6150 pts/6    S      0:00 bash ./karen
karen is already running
Got signal: 
karen is getting triggered!
Got signal: 
karen is getting triggered!
./karen: line 68: /umbrel/events/triggers/: Is a directory
./karen: line 68: /umbrel/events/triggers/: Is a directory
Got signal: change-password
karen is getting triggered!
This script must only be run on Umbrel OS
Got signal: debug
karen is getting triggered!
No such service: tor
Debug result file generated
Got signal: debug
karen is getting triggered!
No such service: tor
Debug result file generated
karen is running in /umbrel/events
Got signal: 
karen is getting triggered!
Got signal: 
karen is getting triggered!
./karen: line 68: /umbrel/events/triggers/: Is a directory
./karen: line 68: /umbrel/events/triggers/: Is a directory
    178 pts/2    S      0:00 bash ./karen
    228 pts/2    S      0:00 bash ./karen
karen is already running
Got signal: change-password
karen is getting triggered!
This script must only be run on Umbrel OS
Got signal: debug
karen is getting triggered!

Docker containers
-----------------
NAMES                 STATUS
middleware            Up 28 seconds
bitcoin               Restarting (1) 31 seconds ago
lnd                   Restarting (1) 33 seconds ago
nginx                 Up 29 minutes
manager               Up 29 minutes
dashboard             Up 29 minutes
electrs               Restarting (1) 43 seconds ago
umbrel_tor_server_1   Restarting (1) 42 seconds ago
tor                   Up 29 minutes

Umbrel logs
-----------

Attaching to middleware, manager
manager              | ::ffff:10.21.21.2 - - [Mon, 17 Jan 2022 18:33:22 GMT] "GET /v1/apps HTTP/1.0" 304 - "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36"
manager              | 
manager              | umbrel-manager
manager              | ::ffff:10.21.21.2 - - [Mon, 17 Jan 2022 18:33:22 GMT] "GET /v1/apps?installed=1 HTTP/1.0" 304 - "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36"
manager              | 
manager              | umbrel-manager
manager              | ::ffff:10.21.21.2 - - [Mon, 17 Jan 2022 18:33:25 GMT] "GET /v1/apps HTTP/1.0" 304 - "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36"
manager              | 
manager              | umbrel-manager
manager              | ::ffff:10.21.21.2 - - [Mon, 17 Jan 2022 18:33:25 GMT] "GET /v1/apps?installed=1 HTTP/1.0" 304 - "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36"
manager              | 
manager              | umbrel-manager
manager              | ::ffff:10.21.21.2 - - [Mon, 17 Jan 2022 18:33:36 GMT] "GET /v1/system/dashboard-hidden-service HTTP/1.0" 304 - "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36"
manager              | 
manager              | umbrel-manager
manager              | ::ffff:10.21.21.2 - - [Mon, 17 Jan 2022 18:33:36 GMT] "GET /v1/system/info HTTP/1.0" 304 - "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36"
manager              | 
manager              | umbrel-manager
manager              | ::ffff:10.21.21.2 - - [Mon, 17 Jan 2022 18:33:36 GMT] "GET /v1/system/uptime HTTP/1.0" 200 7 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36"
manager              | 
manager              | umbrel-manager
manager              | ::ffff:10.21.21.2 - - [Mon, 17 Jan 2022 18:33:36 GMT] "GET /v1/apps HTTP/1.0" 304 - "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36"
manager              | 
manager              | umbrel-manager
manager              | ::ffff:10.21.21.2 - - [Mon, 17 Jan 2022 18:33:36 GMT] "GET /v1/apps?installed=1 HTTP/1.0" 304 - "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36"
manager              | 
manager              | umbrel-manager
manager              | ::ffff:10.21.21.2 - - [Mon, 17 Jan 2022 18:33:38 GMT] "POST /v1/system/debug HTTP/1.0" 200 17 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36"
manager              | 
manager              | umbrel-manager
middleware           | /v1/bitcoind/info/sync
middleware           | BitcoindError: Unable to obtain peer info
middleware           |     at /app/services/bitcoind.js:24:18
middleware           |     at ClientRequest.<anonymous> (/app/node_modules/bitcoind-rpc/lib/index.js:116:7)
middleware           |     at ClientRequest.emit (events.js:314:20)
middleware           |     at Socket.socketErrorListener (_http_client.js:427:9)
middleware           |     at Socket.emit (events.js:314:20)
middleware           |     at emitErrorNT (internal/streams/destroy.js:92:8)
middleware           |     at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
middleware           |     at /app/node_modules/async-listener/glue.js:188:31
middleware           |     at processTicksAndRejections (internal/process/task_queues.js:84:21)
middleware           | ::ffff:10.21.21.2 - - [Mon, 17 Jan 2022 18:33:32 GMT] "GET /v1/bitcoind/info/sync HTTP/1.0" 500 28 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36"
middleware           | 
middleware           | umbrel-middleware
middleware           | LndUnlocker: Wallet failed to unlock!
middleware           | Unable to obtain peer info
middleware           | /v1/bitcoind/info/sync
middleware           | BitcoindError: Unable to obtain peer info
middleware           |     at /app/services/bitcoind.js:24:18
middleware           |     at ClientRequest.<anonymous> (/app/node_modules/bitcoind-rpc/lib/index.js:116:7)
middleware           |     at ClientRequest.emit (events.js:314:20)
middleware           |     at Socket.socketErrorListener (_http_client.js:427:9)
middleware           |     at Socket.emit (events.js:314:20)
middleware           |     at emitErrorNT (internal/streams/destroy.js:92:8)
middleware           |     at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
middleware           |     at /app/node_modules/async-listener/glue.js:188:31
middleware           |     at processTicksAndRejections (internal/process/task_queues.js:84:21)
middleware           | ::ffff:10.21.21.2 - - [Mon, 17 Jan 2022 18:33:35 GMT] "GET /v1/bitcoind/info/sync HTTP/1.0" 500 28 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36"
middleware           | 
middleware           | umbrel-middleware

Bitcoin Core logs
-----------------

Attaching to bitcoin
bitcoin              | Error: Failed saving settings file:
bitcoin              | - Error: Unable to open settings file /data/.bitcoin/settings.json.tmp for writing
bitcoin              | 
bitcoin              | Error: Failed saving settings file:
bitcoin              | - Error: Unable to open settings file /data/.bitcoin/settings.json.tmp for writing
bitcoin              | 
bitcoin              | Error: Failed saving settings file:
bitcoin              | - Error: Unable to open settings file /data/.bitcoin/settings.json.tmp for writing
bitcoin              | 
bitcoin              | Error: Failed saving settings file:
bitcoin              | - Error: Unable to open settings file /data/.bitcoin/settings.json.tmp for writing
bitcoin              | 
bitcoin              | Error: Failed saving settings file:
bitcoin              | - Error: Unable to open settings file /data/.bitcoin/settings.json.tmp for writing
bitcoin              | 
bitcoin              | Error: Failed saving settings file:
bitcoin              | - Error: Unable to open settings file /data/.bitcoin/settings.json.tmp for writing
bitcoin              | 
bitcoin              | Error: Failed saving settings file:
bitcoin              | - Error: Unable to open settings file /data/.bitcoin/settings.json.tmp for writing
bitcoin              | 
bitcoin              | Error: Failed saving settings file:
bitcoin              | - Error: Unable to open settings file /data/.bitcoin/settings.json.tmp for writing
bitcoin              | 
bitcoin              | Error: Failed saving settings file:
bitcoin              | - Error: Unable to open settings file /data/.bitcoin/settings.json.tmp for writing
bitcoin              | 
bitcoin              | Error: Failed saving settings file:
bitcoin              | - Error: Unable to open settings file /data/.bitcoin/settings.json.tmp for writing
bitcoin              | 

LND logs
--------

Attaching to lnd
lnd                  | 2022-01-17 18:18:59.710 [WRN] LTND: Error validating config: ValidateConfig: error normalizing RPC listen addrs: parse address 0.0.0.0:10009 failed: dial tcp 10.21.21.11:9050: connect: connection refused
lnd                  | failed to load config: ValidateConfig: error normalizing RPC listen addrs: parse address 0.0.0.0:10009 failed: dial tcp 10.21.21.11:9050: connect: connection refused
lnd                  | 2022-01-17 18:20:00.160 [WRN] LTND: Error validating config: ValidateConfig: error normalizing RPC listen addrs: parse address 0.0.0.0:10009 failed: dial tcp 10.21.21.11:9050: connect: connection refused
lnd                  | failed to load config: ValidateConfig: error normalizing RPC listen addrs: parse address 0.0.0.0:10009 failed: dial tcp 10.21.21.11:9050: connect: connection refused
lnd                  | 2022-01-17 18:21:00.525 [WRN] LTND: Error validating config: ValidateConfig: error normalizing RPC listen addrs: parse address 0.0.0.0:10009 failed: dial tcp 10.21.21.11:9050: connect: connection refused
lnd                  | failed to load config: ValidateConfig: error normalizing RPC listen addrs: parse address 0.0.0.0:10009 failed: dial tcp 10.21.21.11:9050: connect: connection refused
lnd                  | 2022-01-17 18:22:00.976 [WRN] LTND: Error validating config: ValidateConfig: error normalizing RPC listen addrs: parse address 0.0.0.0:10009 failed: dial tcp 10.21.21.11:9050: connect: connection refused
lnd                  | failed to load config: ValidateConfig: error normalizing RPC listen addrs: parse address 0.0.0.0:10009 failed: dial tcp 10.21.21.11:9050: connect: connection refused
lnd                  | 2022-01-17 18:23:01.306 [WRN] LTND: Error validating config: ValidateConfig: error normalizing RPC listen addrs: parse address 0.0.0.0:10009 failed: dial tcp 10.21.21.11:9050: connect: connection refused
lnd                  | failed to load config: ValidateConfig: error normalizing RPC listen addrs: parse address 0.0.0.0:10009 failed: dial tcp 10.21.21.11:9050: connect: connection refused
lnd                  | 2022-01-17 18:24:01.654 [WRN] LTND: Error validating config: ValidateConfig: error normalizing RPC listen addrs: parse address 0.0.0.0:10009 failed: dial tcp 10.21.21.11:9050: connect: connection refused
lnd                  | failed to load config: ValidateConfig: error normalizing RPC listen addrs: parse address 0.0.0.0:10009 failed: dial tcp 10.21.21.11:9050: connect: connection refused
lnd                  | 2022-01-17 18:25:02.063 [WRN] LTND: Error validating config: ValidateConfig: error normalizing RPC listen addrs: parse address 0.0.0.0:10009 failed: dial tcp 10.21.21.11:9050: connect: connection refused
lnd                  | failed to load config: ValidateConfig: error normalizing RPC listen addrs: parse address 0.0.0.0:10009 failed: dial tcp 10.21.21.11:9050: connect: connection refused
lnd                  | 2022-01-17 18:26:02.415 [WRN] LTND: Error validating config: ValidateConfig: error normalizing RPC listen addrs: parse address 0.0.0.0:10009 failed: dial tcp 10.21.21.11:9050: connect: connection refused
lnd                  | failed to load config: ValidateConfig: error normalizing RPC listen addrs: parse address 0.0.0.0:10009 failed: dial tcp 10.21.21.11:9050: connect: connection refused
lnd                  | 2022-01-17 18:27:03.048 [WRN] LTND: Error validating config: ValidateConfig: error normalizing RPC listen addrs: parse address 0.0.0.0:10009 failed: dial tcp 10.21.21.11:9050: connect: connection refused
lnd                  | failed to load config: ValidateConfig: error normalizing RPC listen addrs: parse address 0.0.0.0:10009 failed: dial tcp 10.21.21.11:9050: connect: connection refused
lnd                  | 2022-01-17 18:28:03.419 [WRN] LTND: Error validating config: ValidateConfig: error normalizing RPC listen addrs: parse address 0.0.0.0:10009 failed: dial tcp 10.21.21.11:9050: connect: connection refused
lnd                  | failed to load config: ValidateConfig: error normalizing RPC listen addrs: parse address 0.0.0.0:10009 failed: dial tcp 10.21.21.11:9050: connect: connection refused
lnd                  | 2022-01-17 18:29:04.153 [WRN] LTND: Error validating config: ValidateConfig: error normalizing RPC listen addrs: parse address 0.0.0.0:10009 failed: dial tcp 10.21.21.11:9050: connect: connection refused
lnd                  | failed to load config: ValidateConfig: error normalizing RPC listen addrs: parse address 0.0.0.0:10009 failed: dial tcp 10.21.21.11:9050: connect: connection refused
lnd                  | 2022-01-17 18:30:04.646 [WRN] LTND: Error validating config: ValidateConfig: error normalizing RPC listen addrs: parse address 0.0.0.0:10009 failed: dial tcp 10.21.21.11:9050: connect: connection refused
lnd                  | failed to load config: ValidateConfig: error normalizing RPC listen addrs: parse address 0.0.0.0:10009 failed: dial tcp 10.21.21.11:9050: connect: connection refused
lnd                  | 2022-01-17 18:31:05.105 [WRN] LTND: Error validating config: ValidateConfig: error normalizing RPC listen addrs: parse address 0.0.0.0:10009 failed: dial tcp 10.21.21.11:9050: connect: connection refused
lnd                  | failed to load config: ValidateConfig: error normalizing RPC listen addrs: parse address 0.0.0.0:10009 failed: dial tcp 10.21.21.11:9050: connect: connection refused
lnd                  | 2022-01-17 18:32:05.642 [WRN] LTND: Error validating config: ValidateConfig: error normalizing RPC listen addrs: parse address 0.0.0.0:10009 failed: dial tcp 10.21.21.11:9050: connect: connection refused
lnd                  | failed to load config: ValidateConfig: error normalizing RPC listen addrs: parse address 0.0.0.0:10009 failed: dial tcp 10.21.21.11:9050: connect: connection refused
lnd                  | 2022-01-17 18:33:06.025 [WRN] LTND: Error validating config: ValidateConfig: error normalizing RPC listen addrs: parse address 0.0.0.0:10009 failed: dial tcp 10.21.21.11:9050: connect: connection refused
lnd                  | failed to load config: ValidateConfig: error normalizing RPC listen addrs: parse address 0.0.0.0:10009 failed: dial tcp 10.21.21.11:9050: connect: connection refused

electrs logs
--------

Attaching to electrs
electrs              | Error: please use `log_filters` to set logging verbosity
electrs              | Error: please use `log_filters` to set logging verbosity
electrs              | Error: please use `log_filters` to set logging verbosity
electrs              | Error: please use `log_filters` to set logging verbosity
electrs              | Error: please use `log_filters` to set logging verbosity
electrs              | Error: please use `log_filters` to set logging verbosity
electrs              | Error: please use `log_filters` to set logging verbosity
electrs              | Error: please use `log_filters` to set logging verbosity
electrs              | Error: please use `log_filters` to set logging verbosity
electrs              | Error: please use `log_filters` to set logging verbosity
electrs              | Error: please use `log_filters` to set logging verbosity
electrs              | Error: please use `log_filters` to set logging verbosity
electrs              | Error: please use `log_filters` to set logging verbosity
electrs              | Error: please use `log_filters` to set logging verbosity
electrs              | Error: please use `log_filters` to set logging verbosity
electrs              | Error: please use `log_filters` to set logging verbosity
electrs              | Error: please use `log_filters` to set logging verbosity
electrs              | Error: please use `log_filters` to set logging verbosity
electrs              | Error: please use `log_filters` to set logging verbosity
electrs              | Error: please use `log_filters` to set logging verbosity
electrs              | Error: please use `log_filters` to set logging verbosity
electrs              | Error: please use `log_filters` to set logging verbosity
electrs              | Error: please use `log_filters` to set logging verbosity
electrs              | Error: please use `log_filters` to set logging verbosity
electrs              | Error: please use `log_filters` to set logging verbosity
electrs              | Error: please use `log_filters` to set logging verbosity
electrs              | Error: please use `log_filters` to set logging verbosity
electrs              | Error: please use `log_filters` to set logging verbosity
electrs              | Error: please use `log_filters` to set logging verbosity
electrs              | Error: please use `log_filters` to set logging verbosity

Tor logs
--------

================
==== Result ====
================
The debug script did not automatically detect any issues with your Umbrel.
```

**Comment by Hukuma1** [comment]
Completely nuking everything and starting fresh somehow fixed it. Not sure how/why, but closing this out.
