### ISSUE TITLE
Uninstall script segfaults when trying to remove TailScale sidecar container

### ISSUE THREAD

**Issue by YellowWords** [getumbrel/umbrel#1512]
I was messing around with Lidarr recently, but when I tried to uninstall it the UI got stuck and didn't do anything. Eventually I ran the uninstall script instead and got the following error:

```
% sudo ./app uninstall lidarr
Removing images for app lidarr...
    "tailscale",
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0xf735b5]

goroutine 37 [running]:
github.com/docker/compose/v2/pkg/compose.(*composeService).getServiceImages(0x0, {0x1, 0x0, 0x0, {0x7fff2ace98c4, 0x3}, 0x0}, {0x7fff2ace9789, 0x6})
	github.com/docker/compose/v2/pkg/compose/down.go:143 +0x75
github.com/docker/compose/v2/pkg/compose.(*composeService).ensureImagesDown(0xc000336380, {0x1444488, 0xc0005500c0}, {0x7fff2ace9789, 0x6}, {0x1, 0x0, 0x0, {0x7fff2ace98c4, 0x3}, ...}, ...)
	github.com/docker/compose/v2/pkg/compose/down.go:118 +0xc8
github.com/docker/compose/v2/pkg/compose.(*composeService).down(0xc000336380, {0x1444488, 0xc0005500c0}, {0x7fff2ace9789, 0x6}, {0x1, 0x0, 0x0, {0x7fff2ace98c4, 0x3}, ...})
	github.com/docker/compose/v2/pkg/compose/down.go:84 +0x4b4
github.com/docker/compose/v2/pkg/compose.(*composeService).Down.func1({0x1444488, 0xc0005500c0})
	github.com/docker/compose/v2/pkg/compose/down.go:38 +0x85
github.com/docker/compose/v2/pkg/progress.Run.func1({0x1444488, 0xc0005500c0})
	github.com/docker/compose/v2/pkg/progress/writer.go:61 +0x27
github.com/docker/compose/v2/pkg/progress.RunWithStatus.func2()
	github.com/docker/compose/v2/pkg/progress/writer.go:82 +0x87
golang.org/x/sync/errgroup.(*Group).Go.func1()
	golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 +0x67
created by golang.org/x/sync/errgroup.(*Group).Go
	golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:54 +0x92
```

**Comment by YellowWords** [comment]
I am now getting the same error for uninstalling other other apps as well - Is it trying to remove a TailScale sidecar container? How to solve this?

**Comment by nevets963** [comment]
@YellowWords Can you check if your system has enough available memory? Can you post back what this returns? `free -m`?

**Comment by YellowWords** [comment]
Sure thing:

```
              total        used        free      shared  buff/cache   available
Mem:           7836        3450         956        1363        3429        2727
Swap:          8095        2047        6048

```
