### ISSUE TITLE
Electrs suddenly fails to connect

### ISSUE THREAD

**Issue by ardevd** [getumbrel/umbrel#1531]
After today's LND bug (and subsequent update) Elects doesnt seem to function anymore.

```
umbrel-middleware
version error:  Error: connect EHOSTUNREACH 10.21.21.10:50001
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16) {
  errno: -113,
  code: 'EHOSTUNREACH',
  syscall: 'connect',
  address: '10.21.21.10',
  port: 50001
}
::ffff:10.21.0.18 - - [Tue, 01 Nov 2022 22:05:23 GMT] "GET /v1/electrs/version HTTP/1.1" 500 93 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:106.0) Gecko/20100101 Firefox/106.0"

umbrel-middleware
syncPercent error:  Error: close connect
    at /app/node_modules/@lily-technologies/electrum-client/lib/client.js:230:37
    at Array.forEach (<anonymous>)
    at ElectrumClient.onClose (/app/node_modules/@lily-technologies/electrum-client/lib/client.js:229:44)
    at ElectrumClient.onClose (/app/node_modules/@lily-technologies/electrum-client/index.js:69:9)
    at Socket.<anonymous> (/app/node_modules/@lily-technologies/electrum-client/lib/client.js:60:9)
    at Socket.emit (node:events:527:28)
    at TCP.<anonymous> (node:net:709:12)
::ffff:10.21.0.18 - - [Tue, 01 Nov 2022 22:05:23 GMT] "GET /v1/electrs/syncPercent HTTP/1.1" 500 2 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:106.0) Gecko/20100101 Firefox/106.0"

umbrel-middleware
Electrum attempting reconnect...
/app/node_modules/@lily-technologies/electrum-client/lib/client.js:206
			throw new Error("Error getting callback while handling response");
			^

Error: Error getting callback while handling response
    at ElectrumClient.response (/app/node_modules/@lily-technologies/electrum-client/lib/client.js:206:10)
    at ElectrumClient.onMessage (/app/node_modules/@lily-technologies/electrum-client/lib/client.js:216:10)
    at /app/node_modules/@lily-technologies/electrum-client/lib/client.js:21:9
    at MessageParser.recursiveParser (/app/node_modules/@lily-technologies/electrum-client/lib/util.js:26:3)
    at MessageParser.run (/app/node_modules/@lily-technologies/electrum-client/lib/util.js:61:21)
    at ElectrumClient.onRecv (/app/node_modules/@lily-technologies/electrum-client/lib/client.js:236:11)
    at Socket.<anonymous> (/app/node_modules/@lily-technologies/electrum-client/lib/client.js:64:9)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:285:11)
npm ERR! Lifecycle script `start` failed with error: 
npm ERR! Error: command failed 
npm ERR!   in workspace: umbrel-electrs-backend@0.1.12 
npm ERR!   at location: /app/apps/backend 
npm notice 
npm notice New minor version of npm available! 8.11.0 -> 8.19.2
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v8.19.2>
npm notice Run `npm install -g npm@8.19.2` to update!
npm notice 
```

And then the entire container crashes.

**Comment by nevets963** [comment]
An update for Electrs v0.9.9 rolled out about 30 minutes ago. Can you install v0.9.9 and see if the problem still persists?

**Comment by nillawafa** [comment]
I can't connect using version 0.9.9

**Comment by KushGene** [comment]
> An update for Electrs v0.9.9 rolled out about 30 minutes ago. Can you install v0.9.9 and see if the problem still persists?

How to update?

**Comment by nevets963** [comment]
@KushGene App updates can be seen in the App Store, you will see the following button:
<img width="1396" alt="Screenshot 2022-12-18 at 14 37 37" src="https://user-images.githubusercontent.com/1112574/208304461-e9eae0d0-e66d-47e5-b21a-cf0954ea046d.png">

**Comment by riegersan** [comment]
I have a similar problem since some days with Version 0.10.2

`Electrum attempting reconnect...
syncPercent error:  Error: close connect
    at /app/node_modules/@lily-technologies/electrum-client/lib/client.js:230:37
    at Array.forEach (<anonymous>)
    at ElectrumClient.onClose (/app/node_modules/@lily-technologies/electrum-client/lib/client.js:229:44)
    at ElectrumClient.onClose (/app/node_modules/@lily-technologies/electrum-client/index.js:69:9)
    at Socket.<anonymous> (/app/node_modules/@lily-technologies/electrum-client/lib/client.js:60:9)
Starting electrs 0.10.2 on x86_64 linux with Config { network: Bitcoin, db_path: "/data/db/bitcoin", db_log_dir: None, daemon_dir: "/data/.bitcoin", daemon_auth: CookieFile("/data/.bitcoin/.cookie"), daemon_rpc_addr: 10.21.21.8:8332, daemon_p2p_addr: 10.21.21.8:8333, electrum_rpc_addr: 0.0.0.0:50001, monitoring_addr: 127.0.0.1:4224, wait_duration: 10s, jsonrpc_timeout: 15s, index_batch_size: 10, index_lookup_limit: None, reindex_last_blocks: 0, auto_reindex: true, ignore_mempool: false, sync_once: false, skip_block_download_wait: false, disable_electrum_rpc: false, server_banner: "Umbrel Electrs (0.10.2)", signet_magic: f9beb4d9, args: [] }
[2024-08-26T06:35:54.339Z INFO  electrs::metrics::metrics_impl] serving Prometheus metrics on 127.0.0.1:4224
[2024-08-26T06:35:54.339Z INFO  electrs::server] serving Electrum RPC on 0.0.0.0:50001
[2024-08-26T06:35:54.368Z INFO  electrs::db] "/data/db/bitcoin": 205 SST files, 49.271868142 GB, 6.15817247 Grows
[2024-08-26T06:35:55.101Z INFO  electrs::chain] loading 857616 headers, tip=000000000000000000000eebdc7d1097dc0caee5d639ba8a7711cc274f6cc923
[2024-08-26T06:35:55.631Z INFO  electrs::chain] chain updated: tip=000000000000000000000eebdc7d1097dc0caee5d639ba8a7711cc274f6cc923, height=857616
[2024-08-26T06:35:55.638Z INFO  electrs::db] closing DB at /data/db/bitcoin
    at Socket.emit (node:events:527:28)
[2024-08-26T06:35:55.638Z WARN  electrs::p2p] failed to shutdown p2p connection: Transport endpoint is not connected (os error 107)
    at TCP.<anonymous> (node:net:709:12)
Error: electrs failed

Caused by:
    receiving on an empty and disconnected channel
Starting electrs 0.10.2 on x86_64 linux with Config { network: Bitcoin, db_path: "/data/db/bitcoin", db_log_dir: None, daemon_dir: "/data/.bitcoin", daemon_auth: CookieFile("/data/.bitcoin/.cookie"), daemon_rpc_addr: 10.21.21.8:8332, daemon_p2p_addr: 10.21.21.8:8333, electrum_rpc_addr: 0.0.0.0:50001, monitoring_addr: 127.0.0.1:4224, wait_duration: 10s, jsonrpc_timeout: 15s, index_batch_size: 10, index_lookup_limit: None, reindex_last_blocks: 0, auto_reindex: true, ignore_mempool: false, sync_once: false, skip_block_download_wait: false, disable_electrum_rpc: false, server_banner: "Umbrel Electrs (0.10.2)", signet_magic: f9beb4d9, args: [] }
[2024-08-26T06:36:55.881Z INFO  electrs::metrics::metrics_impl] serving Prometheus metrics on 127.0.0.1:4224
[2024-08-26T06:36:55.881Z INFO  electrs::server] serving Electrum RPC on 0.0.0.0:50001
[2024-08-26T06:36:55.904Z INFO  electrs::db] "/data/db/bitcoin": 206 SST files, 49.27186916 GB, 6.158172471 Grows
[2024-08-26T06:36:56.597Z INFO  electrs::chain] loading 857616 headers, tip=000000000000000000000eebdc7d1097dc0caee5d639ba8a7711cc274f6cc923
[2024-08-26T06:36:57.085Z INFO  electrs::chain] chain updated: tip=000000000000000000000eebdc7d1097dc0caee5d639ba8a7711cc274f6cc923, height=857616
[2024-08-26T06:36:57.091Z WARN  electrs::p2p] failed to shutdown p2p connection: Transport endpoint is not connected (os error 107)
[2024-08-26T06:36:57.091Z INFO  electrs::db] closing DB at /data/db/bitcoin
Error: electrs failed

Caused by:
    receiving on an empty and disconnected channel
::ffff:10.21.0.17 - - [Mon, 26 Aug 2024 06:35:26 GMT] "GET /v1/electrs/syncPercent HTTP/1.1" 500 2 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.6 Safari/605.1.15"

umbrel-middleware
Electrum attempting reconnect...
syncPercent error:  Error: connect EHOSTUNREACH 10.21.21.10:50001
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16) {
  errno: -113,
  code: 'EHOSTUNREACH',
  syscall: 'connect',
  address: '10.21.21.10',
  port: 50001
}
::ffff:10.21.0.17 - - [Mon, 26 Aug 2024 06:35:39 GMT] "GET /v1/electrs/syncPercent HTTP/1.1" 500 93 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.6 Safari/605.1.15"
`

I already tried a to restart both, bitcoin and electrum. any ideas?
