### ISSUE TITLE
LND not working for Testnet

### ISSUE THREAD

**Issue by diogopms** [getumbrel/umbrel#1572]
OS: ubuntu

BTC container: OK

LND container:
<img width="1800" alt="image" src="https://user-images.githubusercontent.com/2445019/211035910-32eaf2cf-0659-4c2e-8700-2a4c6a304263.png">

Logs:
```
=====================
= Umbrel debug info =
=====================

Umbrel version
--------------
0.5.3

Memory usage
------------
              total        used        free      shared  buff/cache   available
Mem:            24G        2,4G        1,7G        4,0M         19G         21G
Swap:          979M        0,0K        979M

total: 9.8%
bitcoin: 5.4%
system: 2.9%
lightning: 1.5%

Memory monitor logs
-------------------
  82276 pts/0    S      0:00 bash ./scripts/memory-monitor
Memory monitor is already running
2023-01-04 15:35:01 Memory monitor running!
2023-01-06 14:41:10 Memory monitor running!

Filesystem information
----------------------
Filesystem             Size  Used Avail Use% Mounted on
/dev/mapper/vggc-root   78G   52G   23G  70% /
/dev/mapper/vggc-root   78G   52G   23G  70% /

Karen logs
----------

Stopping bitcoin_bitcoind_1    ... done
Removing bitcoin_app_proxy_1   ... 
Removing bitcoin_server_1      ... 
Removing bitcoin_bitcoind_1    ... 
Removing bitcoin_tor_1         ... 
Removing bitcoin_i2pd_daemon_1 ... 
Removing bitcoin_app_proxy_1   ... done
Removing bitcoin_tor_1         ... done
Removing bitcoin_server_1      ... done
Removing bitcoin_i2pd_daemon_1 ... done
Removing bitcoin_bitcoind_1    ... done
Going to remove bitcoin_app_proxy_1, bitcoin_server_1, bitcoin_bitcoind_1, bitcoin_tor_1, bitcoin_i2pd_daemon_1

Stopping Docker services...

Stopping nginx     ... 
Stopping dashboard ... 
Stopping tor_proxy ... 
Stopping manager   ... 
Stopping auth      ... 
Stopping tor_proxy ... done
Stopping nginx     ... done
Stopping auth      ... done
Stopping dashboard ... done
Stopping manager   ... done
Removing nginx     ... 
Removing dashboard ... 
Removing tor_proxy ... 
Removing manager   ... 
Removing auth      ... 
Removing tor_proxy ... done
Removing dashboard ... done
Removing auth      ... done
Removing manager   ... done
Removing nginx     ... done
Removing network umbrel_main_network
error while removing network: network umbrel_main_network id 868779c7ca045439ba2de5533e116728b9e00bc6b6c7a9932192568e15e4255b has active endpoints
Shutting down instances is not supported by Genesis Cloud
karen is running in /home/ubuntu/umbrel/events
Got signal: 
karen is getting triggered!
Got signal: 
karen is getting triggered!
./karen: line 75: /home/ubuntu/umbrel/events/triggers/: Is a directory
./karen: line 75: /home/ubuntu/umbrel/events/triggers/: Is a directory
Got signal: change-password
karen is getting triggered!
This script must only be run on Umbrel OS
Got signal: debug
karen is getting triggered!

Docker containers
-----------------
NAMES                    STATUS
lightning_app_1          Up 8 minutes
lightning_app_proxy_1    Up 8 minutes
bitcoin_i2pd_daemon_1    Up 8 minutes
bitcoin_server_1         Up 8 minutes
bitcoin_app_proxy_1      Up 8 minutes
lightning_tor_1          Up 8 minutes
bitcoin_tor_1            Up 8 minutes
lightning_lnd_1          Up 50 seconds
bitcoin_bitcoind_1       Up 8 minutes
nginx                    Up 8 minutes
dashboard                Up 8 minutes
manager                  Up 8 minutes
tor_proxy                Up 8 minutes
auth                     Up 8 minutes
electrs_app_1            Up 47 hours
lightning_tor_server_1   Up 47 hours
bitcoin_tor_server_1     Up 47 hours
electrs_app_proxy_1      Up 47 hours
mempool_app_proxy_1      Up 47 hours
electrs_tor_1            Up 47 hours
electrs_electrs_1        Restarting (1) 7 seconds ago
mempool_api_1            Up 47 hours
mempool_web_1            Up 47 hours
mempool_tor_server_1     Up 47 hours
mempool_mariadb_1        Up 47 hours

Umbrel logs
-----------

Attaching to manager
manager      | ::ffff:10.21.0.4 - - [Fri, 06 Jan 2023 14:49:54 GMT] "GET /v1/account/token?token=e6ec8d99851f07d805a2e3ea41e285b025f46876b215214e2fb8e5690a8f47a3 HTTP/1.1" 200 16 "-" "app-proxy/0.0.1"
manager      | 
manager      | umbrel-manager
manager      | ::ffff:10.21.0.4 - - [Fri, 06 Jan 2023 14:49:54 GMT] "GET /v1/account/token?token=e6ec8d99851f07d805a2e3ea41e285b025f46876b215214e2fb8e5690a8f47a3 HTTP/1.1" 200 16 "-" "app-proxy/0.0.1"
manager      | 
manager      | umbrel-manager
manager      | ::ffff:10.21.0.4 - - [Fri, 06 Jan 2023 14:49:54 GMT] "GET /v1/account/token?token=e6ec8d99851f07d805a2e3ea41e285b025f46876b215214e2fb8e5690a8f47a3 HTTP/1.1" 200 16 "-" "app-proxy/0.0.1"
manager      | 
manager      | umbrel-manager
manager      | ::ffff:10.21.0.4 - - [Fri, 06 Jan 2023 14:49:54 GMT] "GET /v1/account/token?token=e6ec8d99851f07d805a2e3ea41e285b025f46876b215214e2fb8e5690a8f47a3 HTTP/1.1" 200 16 "-" "app-proxy/0.0.1"
manager      | 
manager      | umbrel-manager
manager      | ::ffff:10.21.0.4 - - [Fri, 06 Jan 2023 14:49:54 GMT] "GET /v1/account/token?token=e6ec8d99851f07d805a2e3ea41e285b025f46876b215214e2fb8e5690a8f47a3 HTTP/1.1" 200 16 "-" "app-proxy/0.0.1"
manager      | 
manager      | umbrel-manager
manager      | ::ffff:10.21.0.4 - - [Fri, 06 Jan 2023 14:49:54 GMT] "GET /v1/account/token?token=e6ec8d99851f07d805a2e3ea41e285b025f46876b215214e2fb8e5690a8f47a3 HTTP/1.1" 200 16 "-" "app-proxy/0.0.1"
manager      | 
manager      | umbrel-manager
manager      | ::ffff:10.21.0.4 - - [Fri, 06 Jan 2023 14:49:54 GMT] "GET /v1/account/token?token=e6ec8d99851f07d805a2e3ea41e285b025f46876b215214e2fb8e5690a8f47a3 HTTP/1.1" 200 16 "-" "app-proxy/0.0.1"
manager      | 
manager      | umbrel-manager
manager      | ::ffff:10.21.21.2 - - [Fri, 06 Jan 2023 14:49:56 GMT] "POST /v1/system/debug HTTP/1.0" 200 17 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
manager      | 
manager      | umbrel-manager
manager      | ::ffff:10.21.21.2 - - [Fri, 06 Jan 2023 14:49:57 GMT] "GET /v1/system/debug-result HTTP/1.0" 200 23 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
manager      | 
manager      | umbrel-manager
manager      | ::ffff:10.21.21.2 - - [Fri, 06 Jan 2023 14:49:58 GMT] "GET /v1/system/debug-result HTTP/1.0" 304 - "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
manager      | 
manager      | umbrel-manager

Tor Proxy logs
--------

Attaching to tor_proxy
tor_proxy    | Jan 06 14:41:18.000 [notice] Bootstrapped 62% (loading_descriptors): Loading relay descriptors
tor_proxy    | Jan 06 14:41:18.000 [notice] Bootstrapped 67% (loading_descriptors): Loading relay descriptors
tor_proxy    | Jan 06 14:41:18.000 [notice] Bootstrapped 73% (loading_descriptors): Loading relay descriptors
tor_proxy    | Jan 06 14:41:18.000 [notice] Bootstrapped 75% (enough_dirinfo): Loaded enough directory info to build circuits
tor_proxy    | Jan 06 14:41:19.000 [notice] Bootstrapped 80% (ap_conn): Connecting to a relay to build circuits
tor_proxy    | Jan 06 14:41:19.000 [notice] Bootstrapped 85% (ap_conn_done): Connected to a relay to build circuits
tor_proxy    | Jan 06 14:41:19.000 [notice] Bootstrapped 89% (ap_handshake): Finishing handshake with a relay to build circuits
tor_proxy    | Jan 06 14:41:19.000 [notice] Bootstrapped 90% (ap_handshake_done): Handshake finished with a relay to build circuits
tor_proxy    | Jan 06 14:41:19.000 [notice] Bootstrapped 95% (circuit_create): Establishing a Tor circuit
tor_proxy    | Jan 06 14:41:20.000 [notice] Bootstrapped 100% (done): Done

App logs
--------

bitcoin

Attaching to bitcoin_i2pd_daemon_1, bitcoin_server_1, bitcoin_app_proxy_1, bitcoin_tor_1, bitcoin_bitcoind_1
app_proxy_1    | Validating token: e6ec8d99851f ...
app_proxy_1    | Validating token: e6ec8d99851f ...
app_proxy_1    | Validating token: e6ec8d99851f ...
app_proxy_1    | Validating token: e6ec8d99851f ...
app_proxy_1    | Validating token: e6ec8d99851f ...
app_proxy_1    | Validating token: e6ec8d99851f ...
app_proxy_1    | Validating token: e6ec8d99851f ...
app_proxy_1    | Validating token: e6ec8d99851f ...
app_proxy_1    | Validating token: e6ec8d99851f ...
app_proxy_1    | Validating token: e6ec8d99851f ...
server_1       | umbrel-middleware
server_1       | ::ffff:10.21.0.5 - - [Fri, 06 Jan 2023 14:44:53 GMT] "GET /v1/bitcoind/info/stats HTTP/1.1" 200 114 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
server_1       | 
server_1       | umbrel-middleware
server_1       | ::ffff:10.21.0.5 - - [Fri, 06 Jan 2023 14:44:56 GMT] "GET /v1/bitcoind/info/stats HTTP/1.1" 304 - "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
server_1       | 
server_1       | umbrel-middleware
server_1       | ::ffff:10.21.0.5 - - [Fri, 06 Jan 2023 14:44:57 GMT] "GET /v1/bitcoind/info/connections HTTP/1.1" 200 65 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
server_1       | 
server_1       | umbrel-middleware
bitcoind_1     | 2023-01-06T14:45:05Z New outbound peer connected: version: 70016, blocks=2414916, peer=12 (block-relay-only)
bitcoind_1     | 2023-01-06T14:46:02Z ThreadRPCServer incorrect password attempt from 10.21.21.27:50850
bitcoind_1     | 2023-01-06T14:46:03Z ThreadRPCServer incorrect password attempt from 10.21.21.27:50864
bitcoind_1     | 2023-01-06T14:47:03Z ThreadRPCServer incorrect password attempt from 10.21.21.27:51826
bitcoind_1     | 2023-01-06T14:47:03Z ThreadRPCServer incorrect password attempt from 10.21.21.27:51838
bitcoind_1     | 2023-01-06T14:48:03Z ThreadRPCServer incorrect password attempt from 10.21.21.27:52286
bitcoind_1     | 2023-01-06T14:48:04Z ThreadRPCServer incorrect password attempt from 10.21.21.27:52300
bitcoind_1     | 2023-01-06T14:49:04Z ThreadRPCServer incorrect password attempt from 10.21.21.27:41408
bitcoind_1     | 2023-01-06T14:49:04Z ThreadRPCServer incorrect password attempt from 10.21.21.27:41422
bitcoind_1     | 2023-01-06T14:49:29Z New outbound peer connected: version: 70016, blocks=2414916, peer=14 (block-relay-only)
i2pd_daemon_1  | 14:44:30@320/error - Garlic: Can't handle ECIES-X25519-AEAD-Ratchet message
i2pd_daemon_1  | 14:44:30@320/error - Garlic: Can't handle ECIES-X25519-AEAD-Ratchet message
i2pd_daemon_1  | 14:44:30@320/error - Garlic: Can't handle ECIES-X25519-AEAD-Ratchet message
i2pd_daemon_1  | 14:44:30@320/error - Garlic: Can't handle ECIES-X25519-AEAD-Ratchet message
i2pd_daemon_1  | 14:44:30@320/error - Garlic: Can't handle ECIES-X25519-AEAD-Ratchet message
i2pd_daemon_1  | 14:44:30@320/error - Garlic: Can't handle ECIES-X25519-AEAD-Ratchet message
i2pd_daemon_1  | 14:44:30@320/error - Garlic: Can't handle ECIES-X25519-AEAD-Ratchet message
i2pd_daemon_1  | 14:44:31@320/error - Garlic: Can't handle ECIES-X25519-AEAD-Ratchet message
i2pd_daemon_1  | 14:44:34@320/error - Garlic: Can't handle ECIES-X25519-AEAD-Ratchet message
i2pd_daemon_1  | 14:44:34@320/error - Garlic: Can't handle ECIES-X25519-AEAD-Ratchet message
tor_1          | Jan 06 14:41:24.000 [notice] Bootstrapped 73% (loading_descriptors): Loading relay descriptors
tor_1          | Jan 06 14:41:24.000 [notice] Bootstrapped 75% (enough_dirinfo): Loaded enough directory info to build circuits
tor_1          | Jan 06 14:41:24.000 [notice] Bootstrapped 80% (ap_conn): Connecting to a relay to build circuits
tor_1          | Jan 06 14:41:24.000 [notice] Bootstrapped 85% (ap_conn_done): Connected to a relay to build circuits
tor_1          | Jan 06 14:41:24.000 [notice] Bootstrapped 89% (ap_handshake): Finishing handshake with a relay to build circuits
tor_1          | Jan 06 14:41:24.000 [notice] Bootstrapped 90% (ap_handshake_done): Handshake finished with a relay to build circuits
tor_1          | Jan 06 14:41:24.000 [notice] Bootstrapped 95% (circuit_create): Establishing a Tor circuit
tor_1          | Jan 06 14:41:27.000 [notice] Bootstrapped 100% (done): Done
tor_1          | Jan 06 14:41:53.000 [notice] Have tried resolving or connecting to address '[scrubbed]' at 3 different places. Giving up.
tor_1          | Jan 06 14:44:55.000 [notice] Have tried resolving or connecting to address '[scrubbed]' at 3 different places. Giving up.

lightning

Attaching to lightning_app_1, lightning_app_proxy_1, lightning_tor_1, lightning_lnd_1
tor_1        | Jan 06 14:41:26.000 [notice] Bootstrapped 62% (loading_descriptors): Loading relay descriptors
tor_1        | Jan 06 14:41:26.000 [notice] Bootstrapped 67% (loading_descriptors): Loading relay descriptors
tor_1        | Jan 06 14:41:28.000 [notice] Bootstrapped 73% (loading_descriptors): Loading relay descriptors
tor_1        | Jan 06 14:41:30.000 [notice] Bootstrapped 75% (enough_dirinfo): Loaded enough directory info to build circuits
tor_1        | Jan 06 14:41:30.000 [notice] Bootstrapped 80% (ap_conn): Connecting to a relay to build circuits
tor_1        | Jan 06 14:41:30.000 [notice] Bootstrapped 85% (ap_conn_done): Connected to a relay to build circuits
tor_1        | Jan 06 14:41:31.000 [notice] Bootstrapped 89% (ap_handshake): Finishing handshake with a relay to build circuits
tor_1        | Jan 06 14:41:31.000 [notice] Bootstrapped 90% (ap_handshake_done): Handshake finished with a relay to build circuits
tor_1        | Jan 06 14:41:31.000 [notice] Bootstrapped 95% (circuit_create): Establishing a Tor circuit
tor_1        | Jan 06 14:41:31.000 [notice] Bootstrapped 100% (done): Done
app_1        |     at InterceptingListener._callNext (/app/node_modules/grpc/src/client_interceptors.js:568:42)
app_1        |     at InterceptingListener.onReceiveStatus (/app/node_modules/grpc/src/client_interceptors.js:618:8)
app_1        |     at callback (/app/node_modules/grpc/src/client_interceptors.js:847:24)
app_1        | ::ffff:10.21.0.4 - - [Fri, 06 Jan 2023 14:49:54 GMT] "GET /v1/lnd/lightning/payments HTTP/1.1" 500 108 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
app_1        | 
app_1        | umbrel-middleware
app_1        | Error getting channels:  Unable to list channels
app_1        | ::ffff:10.21.0.4 - - [Fri, 06 Jan 2023 14:49:54 GMT] "GET /v1/lnd/channel HTTP/1.1" 200 - "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
app_1        | 
app_1        | umbrel-middleware
app_proxy_1  | Validating token: e6ec8d99851f ...
app_proxy_1  | Validating token: e6ec8d99851f ...
app_proxy_1  | Validating token: e6ec8d99851f ...
app_proxy_1  | Validating token: e6ec8d99851f ...
app_proxy_1  | Validating token: e6ec8d99851f ...
app_proxy_1  | Validating token: e6ec8d99851f ...
app_proxy_1  | Validating token: e6ec8d99851f ...
app_proxy_1  | Validating token: e6ec8d99851f ...
app_proxy_1  | Validating token: e6ec8d99851f ...
app_proxy_1  | Validating token: e6ec8d99851f ...
lnd_1        | 2023-01-06 14:49:54.585 [ERR] RPCS: [/lnrpc.Lightning/GetTransactions]: the RPC server is in the process of starting up, but not yet ready to accept calls
lnd_1        | 2023-01-06 14:49:54.586 [ERR] RPCS: [/lnrpc.Lightning/GetRecoveryInfo]: the RPC server is in the process of starting up, but not yet ready to accept calls
lnd_1        | 2023-01-06 14:49:54.586 [ERR] RPCS: [/lnrpc.Lightning/ListInvoices]: the RPC server is in the process of starting up, but not yet ready to accept calls
lnd_1        | 2023-01-06 14:49:54.732 [ERR] RPCS: [/lnrpc.Lightning/ListChannels]: the RPC server is in the process of starting up, but not yet ready to accept calls
lnd_1        | 2023-01-06 14:49:54.750 [ERR] RPCS: [/lnrpc.Lightning/ListChannels]: the RPC server is in the process of starting up, but not yet ready to accept calls
lnd_1        | 2023-01-06 14:49:54.751 [ERR] RPCS: [/lnrpc.Lightning/GetInfo]: the RPC server is in the process of starting up, but not yet ready to accept calls
lnd_1        | 2023-01-06 14:49:54.751 [ERR] RPCS: [/lnrpc.Lightning/WalletBalance]: the RPC server is in the process of starting up, but not yet ready to accept calls
lnd_1        | 2023-01-06 14:49:54.751 [ERR] RPCS: [/lnrpc.Lightning/ChannelBalance]: the RPC server is in the process of starting up, but not yet ready to accept calls
lnd_1        | 2023-01-06 14:49:54.759 [ERR] RPCS: [/lnrpc.Lightning/ListPayments]: the RPC server is in the process of starting up, but not yet ready to accept calls
lnd_1        | 2023-01-06 14:49:54.914 [ERR] RPCS: [/lnrpc.Lightning/ListChannels]: the RPC server is in the process of starting up, but not yet ready to accept calls
================
==== Result ====
================
The debug script did not automatically detect any issues with your Umbrel.

```

**Comment by mayankchhabra** [comment]
Sorry about this @diogopms. Have you tried restarting your Umbrel after changing the Bitcoin network? That will ensure that all dependent apps on Bitcoin are also restarted with the correct network value.

**Comment by diogopms** [comment]
This is the screenshot (two windows open) logs from the `lightninglabs/lnd:v0.15.5-beta` on the right and chrome-devtools on the left

**Comment by mayankchhabra** [comment]
Thank you for reporting @diogopms! It indeed turned out to be a bug. We released a new Lightning Node app update which should fix this. Let us know if that resolves your issue!

**Comment by diogopms** [comment]
I will test it today, thanks

**Comment by diogopms** [comment]
It's fixed, thanks @mayankchhabra
