### ISSUE TITLE
no app store on fresh install

### ISSUE THREAD

**Issue by nightmarebd** [getumbrel/umbrel#1684]
i have installed umbrel in a proxmox container, interface is shown. but there is nothing in app-store.
what am i missing?
i use this code "bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/umbrel.sh)" " 

<img width="1512" alt="Screenshot 2023-07-29 at 3 53 28 AM" src="https://github.com/getumbrel/umbrel/assets/29237019/c6f624fd-6413-40c3-969f-3627980ae64c">

**Comment by middleftw** [comment]
Same problem.
I reinstalled it multiple times.
This was in the logs:

```
manager      | umbrel-manager
manager      | Error reading directory: /repos/https---github-com-getumbrel-umbrel-apps-git Error: ENOENT: no such file or directory, scandir '/repos/https---github-com-getumbrel-umbrel-apps-git'
manager      |     at Object.readdirSync (fs.js:955:3)
manager      |     at Object.listDirsInDir (/app/services/disk.js:77:23)
manager      |     at Object.get (/app/logic/apps.js:147:33)
manager      |     at async /app/routes/v1/apps.js:16:18
manager      |     at async /app/utils/safeHandler.js:8:14 {
manager      |   errno: -2,
manager      |   syscall: 'scandir',
manager      |   code: 'ENOENT',
manager      |   path: '/repos/https---github-com-getumbrel-umbrel-apps-git'
manager      | }
```

**Comment by middleftw** [comment]
Thanks, I couldn't run `sudo scripts/repo update` for some reason, git was failing with `git error fatal: early EOFs`. So I manually cloned the repo like this:

```
mkdir /root/umbrel/repos/https---github-com-getumbrel-umbrel-apps-git
cd /root/umbrel/repos/https---github-com-getumbrel-umbrel-apps-git
git clone --depth 1 https://github.com/getumbrel/umbrel-apps.git .
git fetch --unshallow
git pull --all
```

Then I restarted the node and now its working 😃

**Comment by ttooccooll** [comment]
> Thanks, I couldn't run `sudo scripts/repo update` for some reason, git was failing with `git error fatal: early EOFs`. So I manually cloned the repo like this:
> 
> ```
> mkdir /root/umbrel/repos/https---github-com-getumbrel-umbrel-apps-git
> cd /root/umbrel/repos/https---github-com-getumbrel-umbrel-apps-git
> git clone --depth 1 https://github.com/getumbrel/umbrel-apps.git .
> git fetch --unshallow
> git pull --all
> ```
> 
> Then I restarted the node and now its working smiley

So glad I found this!!! I've been working on this for a week and this is the first thing that worked. Thank you!
