### ISSUE TITLE
Node crashed, not able to access funds

### ISSUE THREAD

**Issue by georgeorwell23** [getumbrel/umbrel#1687]
Hello,

I updated Bitcoin Core & Umbrel OS to the latest version, after that all kinds off problems came up.
First Bitcoin Core was not starting and i had to unable i2pd connections, i unabled i2pd in the advanced settings from Bitcoin Core. I restarted the node and it was still not working. Then i deleted the container and edited the docker compose file.

Now nothing is working, i tried to close the channels in Blixt, but now all of the channels are force closed and i can't enter the funds.
Hopefully someone can help me.

Here are the logs:

= Umbrel debug info =
=====================

Umbrel version
--------------
0.5.4

Flashed OS version
-----------------
v0.5.4

Raspberry Pi Model
------------------
Revision        : d03114
Serial          : 10000000e223b965
Model           : Raspberry Pi 4 Model B Rev 1.4

Firmware
--------
May  9 2023 12:16:34
Copyright (c) 2012 Broadcom
version 30aa0d70ab280427ba04ebc718c81d4350b9d394 (clean) (release) (start)

Temperature
-----------
temp=54.5'C

Throttling
----------
throttled=0x0

Memory usage
------------
              total        used        free      shared  buff/cache   available
Mem:           7.8G        2.4G        985M         82M        4.4G        5.2G
Swap:          4.1G          0B        4.1G

total: 30.7%
lightning: 21.8%
electrs: 7.8%
ride-the-lightning: 6.4%
lndg: 5.1%
lightning-shell: 2.4%
jam: 2.3%
system: 0%
bitcoin: 0%

Memory monitor logs
-------------------
2023-08-03 14:04:33 Memory monitor running!
2023-08-03 14:14:46 Memory monitor running!
2023-08-03 17:13:12 Memory monitor running!
2023-08-03 17:22:03 Memory monitor running!
 1085 ?        R      0:00 bash ./scripts/memory-monitor
Memory monitor is already running
2023-08-03 18:16:27 Memory monitor running!
2023-08-03 18:40:40 Memory monitor running!
2023-08-03 19:01:23 Memory monitor running!
2023-06-22 16:44:59 Memory monitor running!

Filesystem information
----------------------
Filesystem      Size  Used Avail Use% Mounted on
/dev/root       117G  3.2G  109G   3% /
/dev/sda1       916G  641G  229G  74% /home/umbrel/umbrel

Startup service logs
--------------------
Aug 03 19:31:09 umbrel umbrel startup[1889]: Creating electrs_electrs_1 ...
Aug 03 19:31:09 umbrel umbrel startup[1889]: Creating electrs_tor_server_1 ...
Aug 03 19:31:09 umbrel umbrel startup[1889]: Creating electrs_tor_1        ...
Aug 03 19:31:09 umbrel umbrel startup[1889]: Creating electrs_app_proxy_1  ...
Aug 03 19:31:10 umbrel umbrel startup[1889]: Creating lightning_app_proxy_1  ... done
Aug 03 19:31:10 umbrel umbrel startup[1889]: Creating lndg_web_1        ... done
Aug 03 19:31:10 umbrel umbrel startup[1889]: Creating lndg_tor_server_1 ... done
Aug 03 19:31:11 umbrel umbrel startup[1889]: Creating lightning_app_1        ... done
Aug 03 19:31:11 umbrel umbrel startup[1889]: Creating lightning_tor_server_1 ... done
Aug 03 19:31:12 umbrel umbrel startup[1889]: Creating lightning_tor_1        ... done
Aug 03 19:31:13 umbrel umbrel startup[1889]: Creating jam_web_1        ... done
Aug 03 19:31:15 umbrel umbrel startup[1889]: Creating jam_app_proxy_1  ... done
Aug 03 19:31:15 umbrel umbrel startup[1889]: Creating ride-the-lightning_boltz_1      ... done
Aug 03 19:31:15 umbrel umbrel startup[1889]: Creating lightning_lnd_1        ... done
Aug 03 19:31:15 umbrel umbrel startup[1889]: Creating ride-the-lightning_tor_server_1 ... done
Aug 03 19:31:15 umbrel umbrel startup[1889]: Creating jam_tor_server_1 ... done
Aug 03 19:31:16 umbrel umbrel startup[1889]: Creating lndg_app_proxy_1  ... done
Aug 03 19:31:16 umbrel umbrel startup[1889]: Creating ride-the-lightning_web_1        ... done
Aug 03 19:31:16 umbrel umbrel startup[1889]: Creating ride-the-lightning_app_proxy_1  ... done
Aug 03 19:31:17 umbrel umbrel startup[1889]: Creating electrs_tor_1        ... done
Aug 03 19:31:17 umbrel umbrel startup[1889]: Creating electrs_tor_server_1 ... done
Aug 03 19:31:18 umbrel umbrel startup[1889]: Creating electrs_app_proxy_1  ... done
Aug 03 19:31:18 umbrel umbrel startup[1889]: Creating electrs_electrs_1    ... done
Aug 03 19:31:18 umbrel umbrel startup[1889]: Creating electrs_app_1        ...
Aug 03 19:31:21 umbrel umbrel startup[1889]: Creating electrs_app_1        ... done
Aug 03 19:31:22 umbrel umbrel startup[1889]: Umbrel is now accessible at
Aug 03 19:31:22 umbrel umbrel startup[1889]:   http://umbrel.local
Aug 03 19:31:22 umbrel umbrel startup[1889]:   http://192.168.1.110
Aug 03 19:31:22 umbrel systemd[1]: Started Umbrel Startup Service.

External storage service logs
-----------------------------
Jun 22 16:44:16 umbrel external storage mounter[513]:         now = Thu Jun 22 16:44:12 2023) is in the future.
Jun 22 16:44:16 umbrel external storage mounter[513]: Fix? yes
Jun 22 16:44:16 umbrel external storage mounter[513]: Pass 1: Checking inodes, blocks, and sizes
Jun 22 16:44:22 umbrel external storage mounter[513]: Pass 2: Checking directory structure
Jun 22 16:44:25 umbrel external storage mounter[513]: Pass 3: Checking directory connectivity
Jun 22 16:44:25 umbrel external storage mounter[513]: Pass 4: Checking reference counts
Jun 22 16:44:31 umbrel external storage mounter[513]: Pass 5: Checking group summary information
Jun 22 16:44:31 umbrel external storage mounter[513]: Free blocks count wrong (72361482, counted=72310937).
Jun 22 16:44:31 umbrel external storage mounter[513]: Fix? yes
Jun 22 16:44:31 umbrel external storage mounter[513]: Free inodes count wrong (60707884, counted=60706067).
Jun 22 16:44:31 umbrel external storage mounter[513]: Fix? yes
Jun 22 16:44:31 umbrel external storage mounter[513]: umbrel: ***** FILE SYSTEM WAS MODIFIED *****
Jun 22 16:44:31 umbrel external storage mounter[513]: umbrel: 348909/61054976 files (4.9% non-contiguous), 171879271/244190208 blocks
Jun 22 16:44:32 umbrel external storage mounter[513]: Mounting partition...
Jun 22 16:44:32 umbrel external storage mounter[513]: Checking if device contains an Umbrel install...
Jun 22 16:44:32 umbrel external storage mounter[513]: Yes, it contains an Umbrel install
Jun 22 16:44:32 umbrel external storage mounter[513]: Bind mounting external storage over local Umbrel installation...
Jun 22 16:44:32 umbrel external storage mounter[513]: Bind mounting external storage over local Docker data dir...
Jun 22 16:44:32 umbrel external storage mounter[513]: Bind mounting external storage to /swap
Jun 22 16:44:32 umbrel external storage mounter[513]: Bind mounting SD card root at /sd-card...
Jun 22 16:44:32 umbrel external storage mounter[513]: Checking Umbrel root is now on external storage...
Jun 22 16:44:33 umbrel external storage mounter[513]: Checking /var/lib/docker is now on external storage...
Jun 22 16:44:33 umbrel external storage mounter[513]: Checking /swap is now on external storage...
Jun 22 16:44:33 umbrel external storage mounter[513]: Setting up swapfile
Jun 22 16:44:34 umbrel external storage mounter[513]: Setting up swapspace version 1, size = 4 GiB (4294963200 bytes)
Jun 22 16:44:34 umbrel external storage mounter[513]: no label, UUID=355a5864-223d-4890-a0bf-87e67b2c51af
Jun 22 16:44:34 umbrel external storage mounter[513]: Checking SD Card root is bind mounted at /sd-root...
Jun 22 16:44:34 umbrel external storage mounter[513]: Starting external drive mount monitor...
Jun 22 16:44:34 umbrel external storage mounter[513]: Mount script completed successfully!
Jun 22 16:44:34 umbrel systemd[1]: Started External Storage Mounter.

External storage SD card update service logs
--------------------------------------------
-- Logs begin at Thu 2019-02-14 10:11:58 UTC, end at Fri 2023-08-04 05:04:09 UTC. --
Jun 22 16:44:59 umbrel systemd[1]: Starting External Storage SDcard Updater...
Jun 22 16:44:59 umbrel external storage updater[1812]: Checking if SD card Umbrel is newer than external storage...
Jun 22 16:44:59 umbrel external storage updater[1812]: No, SD version is not newer, exiting.
Jun 22 16:44:59 umbrel systemd[1]: Started External Storage SDcard Updater.

Karen logs
----------

Saving app lightning-shell in DB...
Successfully installed app lightning-shell
Got signal: backup
karen is getting triggered!
Deriving keys...
Creating backup...
Adding random padding...
1+0 records in
1+0 records out
4099 bytes (4.1 kB, 4.0 KiB) copied, 0.000260739 s, 15.7 MB/s
Creating encrypted tarball...
backup/
backup/channel.backup
backup/.padding
gpg: directory '/root/.gnupg' created
gpg: keybox '/root/.gnupg/pubring.kbx' created
Uploading backup...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6474  100   146  100  6328     61   2670  0:00:02  0:00:02 --:--:--  2732
{"message":"Successfully uploaded backup 1691103438176.tar.gz.pgp for backup ID 2d9e2af53e673df8bc18b07d53cc797c9051fae2ecba4ed956c3dc58ed3cc874"}
=============================
====== Backup success =======
=============================
Got signal: backup
karen is getting triggered!
Deriving keys...
Creating backup...
Adding random padding...
1+0 records in
1+0 records out
4601 bytes (4.6 kB, 4.5 KiB) copied, 0.000341628 s, 13.5 MB/s
Creating encrypted tarball...
backup/
backup/channel.backup
backup/.padding
Uploading backup...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6972  100   146  100  6826    166   7774 --:--:-- --:--:-- --:--:--  7931
{"message":"Successfully uploaded backup 1691106802014.tar.gz.pgp for backup ID 2d9e2af53e673df8bc18b07d53cc797c9051fae2ecba4ed956c3dc58ed3cc874"}
=============================
====== Backup success =======
=============================
Got signal: debug
karen is getting triggered!
The Compose file '/home/umbrel/umbrel/app-data/bitcoin/docker-compose.yml' is invalid because:
Unsupported config option for services.i2pd_daemon: 'default'
services.i2pd_daemon.networks contains an invalid type, it should be an array, or an object
Debug result file generated

Docker containers
-----------------
NAMES                             STATUS
lightning-shell_tor_server_1      Up 9 hours
lightning-shell_app_proxy_1       Up 9 hours
lightning-shell_web_1             Up 9 hours
electrs_app_1                     Up 10 hours
electrs_app_proxy_1               Up 10 hours
electrs_tor_server_1              Up 10 hours
electrs_electrs_1                 Up Less than a second
electrs_tor_1                     Up 10 hours
ride-the-lightning_tor_server_1   Up 10 hours
ride-the-lightning_boltz_1        Up 10 hours
ride-the-lightning_app_proxy_1    Up 10 hours
ride-the-lightning_web_1          Up 10 hours
jam_web_1                         Up 10 hours
jam_app_proxy_1                   Up 10 hours
jam_tor_server_1                  Up 10 hours
lndg_app_proxy_1                  Up 10 hours
lndg_tor_server_1                 Up 10 hours
lightning_app_1                   Up 10 hours
lndg_web_1                        Up 10 hours
lightning_tor_server_1            Up 10 hours
lightning_lnd_1                   Up 10 hours
lightning_tor_1                   Up 10 hours
lightning_app_proxy_1             Up 10 hours
nginx                             Up 10 hours
tor_proxy                         Up 10 hours
dashboard                         Up 10 hours
auth                              Up 10 hours
manager                           Up 10 hours
tor_server                        Up 10 hours

Umbrel logs
-----------

Attaching to manager
manager      | ::ffff:10.21.21.2 - - [Fri, 04 Aug 2023 05:04:06 GMT] "GET /v1/system/update-status HTTP/1.0" 304 - "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36"
manager      |
manager      | umbrel-manager
manager      | ::ffff:10.21.21.2 - - [Fri, 04 Aug 2023 05:04:06 GMT] "GET /v1/system/is-sd-card-failing HTTP/1.0" 304 - "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36"
manager      |
manager      | umbrel-manager
manager      | ::ffff:10.21.21.2 - - [Fri, 04 Aug 2023 05:04:07 GMT] "GET /v1/system/temperature HTTP/1.0" 200 2 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36"
manager      |
manager      | umbrel-manager
manager      | ::ffff:10.21.21.2 - - [Fri, 04 Aug 2023 05:04:07 GMT] "GET /v1/apps HTTP/1.0" 304 - "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36"
manager      |
manager      | umbrel-manager
manager      | ::ffff:10.21.21.2 - - [Fri, 04 Aug 2023 05:04:07 GMT] "GET /v1/system/info HTTP/1.0" 304 - "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36"
manager      |
manager      | umbrel-manager
manager      | ::ffff:10.21.21.2 - - [Fri, 04 Aug 2023 05:04:07 GMT] "GET /v1/apps?installed=1 HTTP/1.0" 304 - "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36"
manager      |
manager      | umbrel-manager
manager      | ::ffff:10.21.21.2 - - [Fri, 04 Aug 2023 05:04:07 GMT] "GET /v1/system/memory HTTP/1.0" 200 1007 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36"
manager      |
manager      | umbrel-manager
manager      | ::ffff:10.21.21.2 - - [Fri, 04 Aug 2023 05:04:07 GMT] "GET /v1/system/storage HTTP/1.0" 200 1019 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36"
manager      |
manager      | umbrel-manager
manager      | ::ffff:10.21.21.2 - - [Fri, 04 Aug 2023 05:04:07 GMT] "GET /v1/system/update-status HTTP/1.0" 304 - "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36"
manager      |
manager      | umbrel-manager
manager      | ::ffff:10.21.21.2 - - [Fri, 04 Aug 2023 05:04:07 GMT] "GET /v1/system/get-update HTTP/1.0" 304 - "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36"
manager      |
manager      | umbrel-manager

Tor Proxy logs
--------

Attaching to tor_proxy
tor_proxy    | Aug 03 19:31:05.000 [notice] Bootstrapped 95% (circuit_create): Establishing a Tor circuit
tor_proxy    | Aug 03 19:31:05.000 [notice] Bootstrapped 100% (done): Done
tor_proxy    | Aug 03 21:25:56.000 [warn] Received http status code 404 ("Not found") from server 62.141.37.218:443 while fetching "/tor/keys/fp/EFCBE720AB3A82B99F9E953CD5BF50F7EEFC7B97".
tor_proxy    | Aug 03 23:42:56.000 [warn] Received http status code 404 ("Not found") from server 62.141.37.218:443 while fetching "/tor/keys/fp/EFCBE720AB3A82B99F9E953CD5BF50F7EEFC7B97".
tor_proxy    | Aug 04 00:57:56.000 [warn] Received http status code 404 ("Not found") from server 62.141.37.218:443 while fetching "/tor/keys/fp/EFCBE720AB3A82B99F9E953CD5BF50F7EEFC7B97".
tor_proxy    | Aug 04 01:30:51.000 [notice] Heartbeat: Tor's uptime is 6:00 hours, with 0 circuits open. I've sent 1.53 MB and received 12.40 MB. I've received 2 connections on IPv4 and 0 on IPv6. I've made 14 connections with IPv4 and 0 with IPv6.
tor_proxy    | Aug 04 01:30:51.000 [notice] While bootstrapping, fetched this many bytes: 657846 (consensus network-status fetch); 14103 (authority cert fetch); 10586691 (microdescriptor fetch)
tor_proxy    | Aug 04 01:30:51.000 [notice] While not bootstrapping, fetched this many bytes: 141167 (consensus network-status fetch); 189 (authority cert fetch); 46808 (microdescriptor fetch)
tor_proxy    | Aug 04 02:49:57.000 [warn] Received http status code 404 ("Not found") from server 178.254.24.208:443 while fetching "/tor/keys/fp/EFCBE720AB3A82B99F9E953CD5BF50F7EEFC7B97".
tor_proxy    | Aug 04 04:48:57.000 [warn] Received http status code 404 ("Not found") from server 62.141.37.218:443 while fetching "/tor/keys/fp/EFCBE720AB3A82B99F9E953CD5BF50F7EEFC7B97".

App logs
--------

bitcoin

ERROR: The Compose file '/home/umbrel/umbrel/app-data/bitcoin/docker-compose.yml' is invalid because:
Unsupported config option for services.i2pd_daemon: 'default'
services.i2pd_daemon.networks contains an invalid type, it should be an array, or an object

electrs

Attaching to electrs_app_1, electrs_app_proxy_1, electrs_tor_server_1, electrs_electrs_1, electrs_tor_1
app_1         | > umbrel-electrs@1.0.1 dev:backend
app_1         | > npm run start -w umbrel-electrs-backend
app_1         |
app_1         |
app_1         | > umbrel-electrs-backend@0.1.12 start
app_1         | > node ./bin/www
app_1         |
app_1         | Thu, 03 Aug 2023 19:32:03 GMT morgan deprecated morgan(options): use morgan("default", options) instead at app.js:28:9
app_1         | Thu, 03 Aug 2023 19:32:03 GMT morgan deprecated default format: use combined format at app.js:28:9
app_1         | Listening on port 3006
app_proxy_1   | yarn run v1.22.19
app_proxy_1   | $ node ./bin/www
app_proxy_1   | [HPM] Proxy created: /  -> http://10.21.22.4:3006
app_proxy_1   | Waiting for 10.21.22.4:3006 to open...
app_proxy_1   | Electrs is now ready...
app_proxy_1   | Listening on port: 2102
electrs_1     | Error: electrs failed
electrs_1     |
electrs_1     | Caused by:
electrs_1     |     0: failed to open bitcoind cookie file: /data/.bitcoin/.cookie
electrs_1     |     1: No such file or directory (os error 2)
electrs_1     | Starting electrs 0.9.14 on aarch64 linux with Config { network: Bitcoin, db_path: "/data/db/bitcoin", daemon_dir: "/data/.bitcoin", daemon_auth: CookieFile("/data/.bitcoin/.cookie"), daemon_rpc_addr: 10.21.21.8:8332, daemon_p2p_addr: 10.21.21.8:8333, electrum_rpc_addr: 0.0.0.0:50001, monitoring_addr: 127.0.0.1:4224, wait_duration: 10s, jsonrpc_timeout: 15s, index_batch_size: 10, index_lookup_limit: None, reindex_last_blocks: 0, auto_reindex: true, ignore_mempool: false, sync_once: false, skip_block_download_wait: false, disable_electrum_rpc: false, server_banner: "Umbrel Electrs (0.9.14)", signet_magic: f9beb4d9, args: [] }
electrs_1     | [2023-08-04T05:04:10.010Z INFO  electrs::metrics::metrics_impl] serving Prometheus metrics on 127.0.0.1:4224
electrs_1     | [2023-08-04T05:04:10.010Z INFO  electrs::server] serving Electrum RPC on 0.0.0.0:50001
electrs_1     | [2023-08-04T05:04:10.102Z INFO  electrs::db] "/data/db/bitcoin": 172 SST files, 42.062999797 GB, 5.270134472 Grows
electrs_1     | [2023-08-04T05:04:15.332Z INFO  electrs::chain] loading 801543 headers, tip=00000000000000000000e8f2cc9707e7cf9e5fd2b165cbf56f394a7b6a662270
tor_1         | Aug 03 19:32:06.000 [notice] Bootstrapped 89% (ap_handshake): Finishing handshake with a relay to build circuits
tor_1         | Aug 03 19:32:06.000 [notice] Bootstrapped 90% (ap_handshake_done): Handshake finished with a relay to build circuits
tor_1         | Aug 03 19:32:06.000 [notice] Bootstrapped 95% (circuit_create): Establishing a Tor circuit
tor_1         | Aug 03 19:32:06.000 [notice] Bootstrapped 100% (done): Done
tor_1         | Aug 04 01:31:18.000 [notice] Heartbeat: Tor's uptime is 6:00 hours, with 9 circuits open. I've sent 4.01 MB and received 14.78 MB. I've received 0 connections on IPv4 and 0 on IPv6. I've made 10 connections with IPv4 and 0 with IPv6.
tor_1         | Aug 04 01:31:18.000 [notice] While bootstrapping, fetched this many bytes: 657846 (consensus network-status fetch); 11093 (authority cert fetch); 10586691 (microdescriptor fetch)
tor_1         | Aug 04 01:31:18.000 [notice] While not bootstrapping, fetched this many bytes: 152249 (consensus network-status fetch); 10365 (authority cert fetch); 218553 (microdescriptor fetch)
tor_1         | Aug 04 01:31:18.000 [notice] Heartbeat: Our onion service received 0 v3 INTRODUCE2 cells and attempted to launch 0 rendezvous circuits.
tor_1         | Aug 04 02:05:28.000 [warn] Received http status code 404 ("Not found") from server 89.58.57.25:5742 while fetching "/tor/keys/fp/EFCBE720AB3A82B99F9E953CD5BF50F7EEFC7B97".
tor_1         | Aug 04 02:06:32.000 [notice] No circuits are opened. Relaxed timeout for circuit 302 (a Hidden service: Uploading HS descriptor 4-hop circuit in state doing handshakes with channel state open) to 60000ms. However, it appears the circuit has timed out anyway.

jam

Attaching to jam_web_1, jam_app_proxy_1, jam_tor_server_1
app_proxy_1   | yarn run v1.22.19
app_proxy_1   | $ node ./bin/www
app_proxy_1   | [HPM] Proxy created: /  -> http://jam_web_1:80
app_proxy_1   | Waiting for jam_web_1:80 to open...
web_1         | [WARN  tini (7)] Tini is not running as PID 1 and isn't registered as a child subreaper.
web_1         | Zombie processes will not be re-parented to Tini, so zombie reaping won't work.
web_1         | To fix the problem, use the -s option or set the environment variable TINI_SUBREAPER to register Tini as a child subreaper, or run Tini as PID 1.
web_1         | Remove leftover wallet lockfiles before startup...
web_1         | Waiting for bitcoind to accept RPC requests...

lightning

Attaching to lightning_app_1, lightning_tor_server_1, lightning_lnd_1, lightning_tor_1, lightning_app_proxy_1
app_1         | Waiting for LND...
app_1         | Checking LND status...
app_1         | Waiting for LND...
app_1         | Checking LND status...
app_1         | Waiting for LND...
app_1         | Checking LND status...
app_1         | Waiting for LND...
app_1         | Checking LND status...
app_1         | Waiting for LND...
app_1         | Checking LND status...
app_proxy_1   | Validating token: bc8714e5556f ...
app_proxy_1   | Validating token: bc8714e5556f ...
app_proxy_1   | Validating token: bc8714e5556f ...
app_proxy_1   | Validating token: bc8714e5556f ...
app_proxy_1   | Validating token: bc8714e5556f ...
app_proxy_1   | Validating token: bc8714e5556f ...
app_proxy_1   | Validating token: bc8714e5556f ...
app_proxy_1   | Validating token: bc8714e5556f ...
app_proxy_1   | Validating token: bc8714e5556f ...
app_proxy_1   | Validating token: bc8714e5556f ...
lnd_1         | 2023-08-04 05:03:22.121 [ERR] RPCS: [/lnrpc.Lightning/GetInfo]: wallet locked, unlock it to enable full RPC access
lnd_1         | 2023-08-04 05:03:22.427 [ERR] RPCS: [/routerrpc.Router/SubscribeHtlcEvents]: wallet locked, unlock it to enable full RPC access
lnd_1         | 2023-08-04 05:03:37.135 [ERR] RPCS: [/lnrpc.Lightning/GetInfo]: wallet locked, unlock it to enable full RPC access
lnd_1         | 2023-08-04 05:03:41.579 [ERR] RPCS: [/lnrpc.Lightning/ListPeers]: wallet locked, unlock it to enable full RPC access
lnd_1         | 2023-08-04 05:03:52.144 [ERR] RPCS: [/lnrpc.Lightning/GetInfo]: wallet locked, unlock it to enable full RPC access
lnd_1         | 2023-08-04 05:04:01.681 [ERR] RPCS: [/routerrpc.Router/SubscribeHtlcEvents]: wallet locked, unlock it to enable full RPC access
lnd_1         | 2023-08-04 05:04:02.308 [ERR] RPCS: [/lnrpc.Lightning/ListPeers]: wallet locked, unlock it to enable full RPC access
lnd_1         | 2023-08-04 05:04:07.158 [ERR] RPCS: [/lnrpc.Lightning/GetInfo]: wallet locked, unlock it to enable full RPC access
lnd_1         | 2023-08-04 05:04:22.176 [ERR] RPCS: [/lnrpc.Lightning/GetInfo]: wallet locked, unlock it to enable full RPC access
lnd_1         | 2023-08-04 05:04:22.940 [ERR] RPCS: [/lnrpc.Lightning/ListPeers]: wallet locked, unlock it to enable full RPC access
tor_1         | Aug 03 19:31:53.000 [notice] Bootstrapped 95% (circuit_create): Establishing a Tor circuit
tor_1         | Aug 03 19:31:53.000 [notice] Bootstrapped 100% (done): Done
tor_1         | Aug 03 20:50:20.000 [warn] Received http status code 404 ("Not found") from server 140.238.217.119:143 while fetching "/tor/keys/fp/D586D18309DED4CD6D57C18FDB97EFA96D330566+EFCBE720AB3A82B99F9E953CD5BF50F7EEFC7B97".
tor_1         | Aug 03 22:50:19.000 [warn] Received http status code 404 ("Not found") from server 140.238.217.119:143 while fetching "/tor/keys/fp/D586D18309DED4CD6D57C18FDB97EFA96D330566+EFCBE720AB3A82B99F9E953CD5BF50F7EEFC7B97".
tor_1         | Aug 04 01:31:13.000 [notice] Heartbeat: Tor's uptime is 6:00 hours, with 15 circuits open. I've sent 5.68 MB and received 15.19 MB. I've received 0 connections on IPv4 and 0 on IPv6. I've made 11 connections with IPv4 and 0 with IPv6.
tor_1         | Aug 04 01:31:13.000 [notice] While bootstrapping, fetched this many bytes: 657846 (consensus network-status fetch); 11093 (authority cert fetch); 10586691 (microdescriptor fetch)
tor_1         | Aug 04 01:31:13.000 [notice] While not bootstrapping, fetched this many bytes: 146970 (consensus network-status fetch); 5166 (authority cert fetch); 215196 (microdescriptor fetch)
tor_1         | Aug 04 01:31:13.000 [notice] Heartbeat: Our onion services received 0 v3 INTRODUCE2 cells and attempted to launch 0 rendezvous circuits.
tor_1         | Aug 04 01:54:20.000 [warn] Received http status code 404 ("Not found") from server 140.238.217.119:143 while fetching "/tor/keys/fp/EFCBE720AB3A82B99F9E953CD5BF50F7EEFC7B97".
tor_1         | Aug 04 03:45:24.000 [notice] No circuits are opened. Relaxed timeout for circuit 559 (a Hidden service: Uploading HS descriptor 4-hop circuit in state doing handshakes with channel state open) to 60000ms. However, it appears the circuit has timed out anyway.

lightning-shell

Attaching to lightning-shell_tor_server_1, lightning-shell_app_proxy_1, lightning-shell_web_1
app_proxy_1   | yarn run v1.22.19
app_proxy_1   | $ node ./bin/www
app_proxy_1   | [HPM] Proxy created: /  -> http://lightning-shell_web_1:7681
app_proxy_1   | Waiting for lightning-shell_web_1:7681 to open...
app_proxy_1   | Lightning Shell is now ready...
app_proxy_1   | Listening on port: 7681
app_proxy_1   | Validating token: bc8714e5556f ...
web_1         | [2023/08/03 20:13:18:9086] N:  ++ [vh|0|netlink] (1)
web_1         | [2023/08/03 20:13:18:9368] N:  ++ [vh|1|default||7681] (2)
web_1         | [2023/08/03 20:13:18:9370] N: [null wsi]: lws_socket_bind: source ads 0.0.0.0
web_1         | [2023/08/03 20:13:18:9371] N:  ++ [wsi|1|listen|default||7681] (2)
web_1         | [2023/08/03 20:13:18:9371] N:  Listening on port: 7681
web_1         | [2023/08/03 20:13:21:4770] N:  ++ [wsisrv|0|adopted] (1)
web_1         | [2023/08/03 20:13:21:4876] N:  -- [wsisrv|0|adopted] (0) 10.632ms
web_1         | [2023/08/03 20:13:23:7275] N:  ++ [wsisrv|1|adopted] (1)
web_1         | [2023/08/03 20:13:23:7289] N: HTTP / - 10.21.0.19
web_1         | [2023/08/03 20:13:38:7349] N:  -- [wsisrv|1|adopted] (0) 15.007s

lndg

Attaching to lndg_app_proxy_1, lndg_tor_server_1, lndg_web_1
app_proxy_1   | yarn run v1.22.19
app_proxy_1   | $ node ./bin/www
app_proxy_1   | [HPM] Proxy created: /  -> http://10.21.21.75:8889
app_proxy_1   | Waiting for 10.21.21.75:8889 to open...
app_proxy_1   | LNDg is now ready...
app_proxy_1   | Listening on port: 8889
web_1         | /usr/local/lib/python3.11/site-packages/supervisor/options.py:474: UserWarning: Supervisord is running as root and it is searching for its configuration file in default locations (including its current working directory); you probably want to specify a "-c" argument specifying an absolute path to a configuration file for improved security.
web_1         |   self.warnings.warn(
web_1         | Performing system checks...
web_1         |
web_1         | System check identified no issues (0 silenced).
web_1         | August 03, 2023 - 19:32:19
web_1         | Django version 4.2.2, using settings 'lndg.settings'
web_1         | Starting development server at http://0.0.0.0:8889/
web_1         | Quit the server with CONTROL-C.
web_1         |

ride-the-lightning

Attaching to ride-the-lightning_tor_server_1, ride-the-lightning_boltz_1, ride-the-lightning_app_proxy_1, ride-the-lightning_web_1
app_proxy_1   | yarn run v1.22.19
app_proxy_1   | $ node ./bin/www
app_proxy_1   | [HPM] Proxy created: /  -> http://ride-the-lightning_web_1:3001
app_proxy_1   | Waiting for ride-the-lightning_web_1:3001 to open...
app_proxy_1   | Ride The Lightning is now ready...
app_proxy_1   | Listening on port: 3001
boltz_1       | WARN : 2023/08/04 05:03:22 Could not connect to LND: rpc error: code = Unknown desc = wallet locked, unlock it to enable full RPC access
boltz_1       | INFO : 2023/08/04 05:03:22 Retrying in 15 seconds
boltz_1       | WARN : 2023/08/04 05:03:37 Could not connect to LND: rpc error: code = Unknown desc = wallet locked, unlock it to enable full RPC access
boltz_1       | INFO : 2023/08/04 05:03:37 Retrying in 15 seconds
boltz_1       | WARN : 2023/08/04 05:03:52 Could not connect to LND: rpc error: code = Unknown desc = wallet locked, unlock it to enable full RPC access
boltz_1       | INFO : 2023/08/04 05:03:52 Retrying in 15 seconds
boltz_1       | WARN : 2023/08/04 05:04:07 Could not connect to LND: rpc error: code = Unknown desc = wallet locked, unlock it to enable full RPC access
boltz_1       | INFO : 2023/08/04 05:04:07 Retrying in 15 seconds
boltz_1       | WARN : 2023/08/04 05:04:22 Could not connect to LND: rpc error: code = Unknown desc = wallet locked, unlock it to enable full RPC access
boltz_1       | INFO : 2023/08/04 05:04:22 Retrying in 15 seconds
web_1         | [8/3/2023, 7:31:42 PM] INFO: App => Setting up Application Routes...
web_1         |
web_1         | [8/3/2023, 7:31:42 PM] INFO: App => Application Routes Set.
web_1         |
web_1         | [8/3/2023, 7:31:42 PM] INFO: WebSocketServer => Connecting Websocket Server...
web_1         |
web_1         | [8/3/2023, 7:31:42 PM] INFO: WebSocketServer => Websocket Server Connected.
web_1         |
web_1         | [8/3/2023, 7:31:43 PM] INFO: RTL => Server is up and running, please open the UI at http://localhost:3001 or your proxy configured url.
web_1         |
================
==== Result ====
================
The debug script did not automatically detect any issues with your Umbrel.

**Comment by smolgrrr** [comment]
Helped a user with a similar user the other day. 
Hopefully this thread helps :) https://community.umbrel.com/t/bitcoin-node-stuck-starting/13241/12

**Comment by usernameisJim** [comment]
@georgeorwell23 We want to check next if you're using an unofficially Raspberry Pi 4 Power Supply? 
This is the common cause of a corruption like this

We can also revert to a valid configuration of the docker-compose.yml file via this command:

`sudo scripts/app update bitcoin`

This should fix the error, you can also then restart the system I'd suggest:
`sudo reboot`

Let us know if then you are able to load Bitcoin Node app
