### ISSUE TITLE
umbrel samourai server tracker stops working after umbrel v0.4.1 upgrade 

### ISSUE THREAD

**Issue by lestephane** [getumbrel/umbrel#941]
I ignored the v0.4.0 upgrade, waited for v0.4.1 to be out for at least 10 days (in case there is any serious regression), and upgraded from v0.3.14 to Umbrel v0.4.1 using the upgrade button from the umbrel web dashboard.

- There is now a zero balance shown upon opening my paired Samourai Wallet (after loading for a few seconds)
- The maintenance tool PUSHTX STATUS shows zero pushed transactions. There were transactions before.
- The XPUB tool in the maintenance tool (when given the BIP44 XPUB from the Samourai Wallet) tells me that my Samourai Wallet XPUB is not tracked.

It's like the upgrade wiped out the previous Dojo configuration. Does that seem plausible?

**Comment by lestephane** [comment]
When I download the logs from the web dashboard, there seems to be a stack trace for the samourai server node_1 container, but the stack is truncated, how do I get the *full* logs for node_1.

```
samourai-server

node_1       |     at runMicrotasks (<anonymous>)
node_1       |     at processTicksAndRejections (internal/process/task_queues.js:97:5)
node_1       |     at async StatusRestApi.getStatus (/home/node/app/accounts/status-rest-api.js:44:26)
node_1       |     at async /home/node/app/node_modules/@tinyhttp/app/dist/index.cjs:143:13
node_1       |     at async /home/node/app/node_modules/@tinyhttp/app/dist/index.cjs:354:13
node_1       | 2021-09-01T08:28:41Z  INFO  HttpServer : GET /status?at=...
node_1       | 2021-09-01T08:28:41Z  INFO  HttpServer : GET /status?at=...
node_1       | 2021-09-01T08:28:41Z  INFO  HttpServer : GET /status/schedule?at=...
node_1       | 2021-09-01T08:28:45Z  INFO  Tracker : Processing inactive Mempool (0 transactions)
node_1       | 2021-09-01T08:28:55Z  INFO  Tracker : Processing inactive Mempool (0 transactions)
...
================
==== Result ====
================
The debug script did not automatically detect any issues with your Umbrel.
```

**Comment by lestephane** [comment]
I've got access to the full logs of the node_1 container, if you need more details
